FROM golang:1.23-alpine AS builder
WORKDIR /go/src/app

RUN apk update && apk upgrade && \
  apk --update add git gcc make libc-dev openssh linux-headers

COPY . .
RUN go mod tidy
RUN go install github.com/swaggo/swag/cmd/swag@v1.16.3
RUN swag init --parseDependency --parseInternal -g cmd/main.go
RUN go build -o build/main cmd/*.go
