version: '3.7'
services:
  ollama:
    image: ollama/ollama
    restart: always
    ports:
      - "11435:11434"
    volumes:
      - ./models:/app/models
      - ./entrypoint.sh:/entrypoint.sh
    entrypoint: ["/usr/bin/bash", "/entrypoint.sh"]
  service_miner:
    image:  service_miner
    build:
      context: .
      dockerfile: Dockerfile.Arm
    container_name:  service_miner
    entrypoint: ["/workersv", "-silent",  "-no-update-on-start", "true", ]
    ports:
      - "8000:8000"
    env_file:
      - config.env
    tty: true
    stdin_open: true
    restart: always
    volumes:
      - ./docker-volumes/eternal_ai/infer-results:/home/eternal_ai/infer-results/
      - ./docker-volumes/eternal_ai/database:/database