#!/bin/bash
echo
echo "> Removing old files"
echo
rm -f miner-node
rm -f run-miner-node.sh

echo "> Downloading miner-node"
echo
curl -LJ -o miner-node https://github.com/eternalai-org/miner-node/releases/download/v0.5.5/miner-node-linux-amd64 

echo "> Enter your account private key:"
read ACCOUNT

#check if the account is valid
if [[ ! $ACCOUNT =~ ^[a-fA-F0-9]{64}$ ]]; then
    echo "Invalid account"
    exit 1
fi

echo 
echo "> Enter your lighthouse API:"
read LIGHTHOUSE_API

#check if the lighthouse API is valid
if [[ ! $LIGHTHOUSE_API =~ ^[a-fA-F0-9]{8}\.[a-fA-F0-9]{32}$ ]]; then
    echo "Invalid lighthouse API"
    exit 1
fi

script="
#!/bin/bash

# DO NOT EDIT THIS FILE
# This file was generated by the mining-setup.sh script

./miner-node -account $ACCOUNT -lighthouse-api $LIGHTHOUSE_API
"

echo "> Creating script"
echo
echo "$script" > run-miner-node.sh

echo "> Setting up permissions"
echo
chmod +x run-miner-node.sh
chmod +x miner-node

echo "> Setup complete!"
echo
echo "> To start the miner run:"
echo "-------------------------"
echo "|                       |"
echo "|  ./run-miner-node.sh  |"
echo "|                       |"
echo "-------------------------"